import { db } from '~/server/db';
import { users, userCredits, products } from '~/server/db/schema';
import { eq } from 'drizzle-orm';
import bcrypt from 'bcryptjs';

const INITIAL_CREDITS: Record<string, number> = {
  'nina@demo.de': 25,
  'maxine@demo.de': 15,
  'lucas@demo.de': 30,
  'alex@demo.de': 20,
  'tom@demo.de': 10,
}

async function seed() {
  const passwordHashAdmin = await bcrypt.hash('admin123', 10);
  const passwordHashDemo = await bcrypt.hash('demo123', 10);

  await db.insert(users).values([
    {
      email: 'admin@demo.de',
      name: 'Admin',
      role: 'admin',
      passwordHash: passwordHashAdmin,
      location: 'Nürnberg',
    },
    {
      email: 'nina@demo.de',
      name: 'Nina Neuanfang',
      role: 'mitarbeiter',
      passwordHash: passwordHashDemo,
      location: 'Nürnberg',
    },
    {
      email: 'maxine@demo.de',
      name: 'Maxine Snackliebhaber',
      role: 'mitarbeiter',
      passwordHash: passwordHashDemo,
      location: 'Berlin',
    },
    {
      email: 'lucas@demo.de',
      name: 'Lucas Gesundheitsfan',
      role: 'mitarbeiter',
      passwordHash: passwordHashDemo,
      location: 'Nürnberg',
    },
    {
      email: 'alex@demo.de',
      name: 'Alex Gelegenheitskäufer',
      role: 'mitarbeiter',
      passwordHash: passwordHashDemo,
      location: 'Berlin',
    },
    {
      email: 'tom@demo.de',
      name: 'Tom Schnellkäufer',
      role: 'mitarbeiter',
      passwordHash: passwordHashDemo,
      location: 'Nürnberg',
    },
  ]).onConflictDoNothing();

  const allUsers = await db.select().from(users)
  
  for (const user of allUsers) {
    const creditAmount = INITIAL_CREDITS[user.email]
    
    if (creditAmount !== undefined) {
      const existing = await db.select().from(userCredits).where(
        eq(userCredits.userId, user.id)
      ).limit(1)
      
      if (!existing[0]) {
        await db.insert(userCredits).values({
          userId: user.id,
          balance: creditAmount.toFixed(2),
          lastRechargedAt: new Date(),
        })
        console.log(`Added ${creditAmount}€ credits for ${user.email}`)
      }
    }
  }

  const productData = [
    {
      name: 'Bio Apfel',
      description: 'Frischer Bio-Apfel aus regionalem Anbau',
      category: 'obst',
      price: '0.80',
      calories: 52,
      protein: 0,
      sugar: 10,
      fat: 0,
      isVegan: true,
      isGlutenFree: true,
      stock: 50,
    },
    {
      name: 'Banane',
      description: 'Reife Banane aus biologischem Anbau',
      category: 'obst',
      price: '0.60',
      calories: 89,
      protein: 1,
      sugar: 12,
      fat: 0,
      isVegan: true,
      isGlutenFree: true,
      stock: 40,
    },
    {
      name: 'Protein Riegel Schoko',
      description: 'Proteinreicher Riegel mit Schokogeschmack',
      category: 'proteinriegel',
      price: '2.50',
      calories: 200,
      protein: 20,
      sugar: 3,
      fat: 8,
      allergens: ['Milch', 'Soja'],
      isVegan: false,
      isGlutenFree: true,
      stock: 25,
    },
    {
      name: 'Protein Riegel Vanille',
      description: 'Proteinreicher Riegel mit Vanillegeschmack',
      category: 'proteinriegel',
      price: '2.50',
      calories: 190,
      protein: 20,
      sugar: 2,
      fat: 7,
      allergens: ['Milch'],
      isVegan: false,
      isGlutenFree: true,
      stock: 20,
    },
    {
      name: 'Veggie Protein Bar',
      description: 'Pflanzlicher Proteinriegel',
      category: 'proteinriegel',
      price: '2.80',
      calories: 180,
      protein: 18,
      sugar: 4,
      fat: 6,
      allergens: ['Soja', 'Nüsse'],
      isVegan: true,
      isGlutenFree: true,
      stock: 15,
    },
    {
      name: 'Chocolate Shake',
      description: 'cremiger Proteinshake mit Schokogeschmack',
      category: 'shakes',
      price: '3.20',
      calories: 150,
      protein: 25,
      sugar: 2,
      fat: 3,
      allergens: ['Milch'],
      isVegan: false,
      isGlutenFree: true,
      stock: 30,
    },
    {
      name: 'Vanille Shake',
      description: 'cremiger Proteinshake mit Vanillegeschmack',
      category: 'shakes',
      price: '3.20',
      calories: 140,
      protein: 25,
      sugar: 1,
      fat: 2,
      allergens: ['Milch'],
      isVegan: false,
      isGlutenFree: true,
      stock: 28,
    },
    {
      name: 'Beeren Shake',
      description: 'cremiger Proteinshake mit Beerenmix',
      category: 'shakes',
      price: '3.50',
      calories: 145,
      protein: 24,
      sugar: 3,
      fat: 2,
      allergens: ['Milch'],
      isVegan: false,
      isGlutenFree: true,
      stock: 22,
    },
    {
      name: 'Vegan Shake Berry',
      description: 'Pflanzlicher Proteinshake mit Beeren',
      category: 'shakes',
      price: '3.80',
      calories: 130,
      protein: 20,
      sugar: 4,
      fat: 2,
      allergens: ['Soja'],
      isVegan: true,
      isGlutenFree: true,
      stock: 18,
    },
    {
      name: 'Schokoriegel Vollmilch',
      description: 'Klassischer Schokoriegel',
      category: 'schokoriegel',
      price: '1.50',
      calories: 230,
      protein: 3,
      sugar: 24,
      fat: 13,
      allergens: ['Milch', 'Soja'],
      isVegan: false,
      isGlutenFree: true,
      stock: 35,
    },
    {
      name: 'Schokoriegel Dunkel',
      description: 'Edler dunkler Schokoriegel 70% Kakao',
      category: 'schokoriegel',
      price: '1.80',
      calories: 210,
      protein: 4,
      sugar: 15,
      fat: 15,
      allergens: ['Soja'],
      isVegan: true,
      isGlutenFree: true,
      stock: 25,
    },
    {
      name: 'Haselnuss-Nougat Riegel',
      description: 'Schokoriegel mit Haselnüssen',
      category: 'schokoriegel',
      price: '1.70',
      calories: 220,
      protein: 4,
      sugar: 20,
      fat: 14,
      allergens: ['Milch', 'Nüsse', 'Soja'],
      isVegan: false,
      isGlutenFree: true,
      stock: 20,
    },
    {
      name: 'Erdnüsse Geröstet',
      description: 'Knusprige geröstete Erdnüsse',
      category: 'nuesse',
      price: '1.20',
      calories: 170,
      protein: 7,
      sugar: 1,
      fat: 14,
      isVegan: true,
      isGlutenFree: true,
      stock: 40,
    },
    {
      name: 'Mandeln',
      description: 'Gesunde Mandeln',
      category: 'nuesse',
      price: '2.00',
      calories: 160,
      protein: 6,
      sugar: 1,
      fat: 14,
      isVegan: true,
      isGlutenFree: true,
      stock: 30,
    },
    {
      name: 'Cashew Kerne',
      description: 'Leckere Cashew Kerne',
      category: 'nuesse',
      price: '2.50',
      calories: 150,
      protein: 5,
      sugar: 2,
      fat: 12,
      isVegan: true,
      isGlutenFree: true,
      stock: 25,
    },
    {
      name: 'Mix Nüsse',
      description: 'Mischung aus verschiedenen Nüssen',
      category: 'nuesse',
      price: '2.80',
      calories: 165,
      protein: 5,
      sugar: 1,
      fat: 15,
      allergens: ['Nüsse'],
      isVegan: true,
      isGlutenFree: true,
      stock: 20,
    },
    {
      name: 'Orangensaft',
      description: 'Frisch gepresster Orangensaft',
      category: 'getraenke',
      price: '2.00',
      calories: 45,
      protein: 1,
      sugar: 10,
      fat: 0,
      isVegan: true,
      isGlutenFree: true,
      stock: 30,
    },
    {
      name: 'Apfelsaft',
      description: 'Bio Apfelsaft aus der Region',
      category: 'getraenke',
      price: '1.80',
      calories: 46,
      protein: 0,
      sugar: 11,
      fat: 0,
      isVegan: true,
      isGlutenFree: true,
      stock: 28,
    },
    {
      name: 'Wasser Medium',
      description: 'Erfrischendes Mineralwasser',
      category: 'getraenke',
      price: '1.00',
      calories: 0,
      protein: 0,
      sugar: 0,
      fat: 0,
      isVegan: true,
      isGlutenFree: true,
      stock: 50,
    },
    {
      name: 'Cola Zero',
      description: 'Cola ohne Zucker',
      category: 'getraenke',
      price: '1.50',
      calories: 0,
      protein: 0,
      sugar: 0,
      fat: 0,
      allergens: ['Koffein'],
      isVegan: true,
      isGlutenFree: true,
      stock: 40,
    },
    {
      name: 'Iso Sport Drink',
      description: 'Isotonisches Sportgetränk',
      category: 'getraenke',
      price: '2.20',
      calories: 30,
      protein: 0,
      sugar: 7,
      fat: 0,
      allergens: ['Koffein'],
      isVegan: true,
      isGlutenFree: true,
      stock: 25,
    },
  ]

  for (const product of productData) {
    await db.insert(products).values(product).onConflictDoNothing()
  }
  console.log('Product seed data inserted successfully');

  console.log('Seed data inserted successfully');
}

seed().catch(console.error);
