// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/25/2026, 11:44:19 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/enricoreinsdorf/Projekte/SnackEase/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/enricoreinsdorf/Projekte/SnackEase/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/enricoreinsdorf/Projekte/SnackEase/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/enricoreinsdorf/Projekte/SnackEase/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/enricoreinsdorf/Projekte/SnackEase/src/plugins/**/*.{js,ts,mjs}","/Users/enricoreinsdorf/Projekte/SnackEase/src/composables/**/*.{js,ts,mjs}","/Users/enricoreinsdorf/Projekte/SnackEase/src/utils/**/*.{js,ts,mjs}","/Users/enricoreinsdorf/Projekte/SnackEase/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/enricoreinsdorf/Projekte/SnackEase/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/enricoreinsdorf/Projekte/SnackEase/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/enricoreinsdorf/Projekte/SnackEase/src/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;